import { Component, OnInit } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
@Component({
  selector: 'lib-user-list',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.css']
})
export class UserListComponent implements OnInit {
  tableColumns: any[] = [];;
  users : any ;
  constructor() {}

  // for time being dummy data
  students = [
    {
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },{
      organization: 'SaasOrg',
      firstName: 'Pooja',
      lastName: 'K',
      email: 'p****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Raju',
      lastName: 'Rastogi',
      email: 'raj****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Farhan',
      lastName: 'Qureshi',
      email: 'qur****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
    {
      organization: 'SaasOrg',
      firstName: 'Ranchordas',
      lastName: 'Chanchad',
      email: 'chan****@yopmail.com',
      mobile: '98635*****',
      status: 'Active',
      role: 'PUBLIC',
    },
  ];

  ngOnInit() {
    this.tableColumns = [
      { field: 'firstName', header: 'First Name' },
      { field: 'lastName', header: 'Last Name' },
      { field: 'role', header: 'Role' },
      { field: 'email', header: 'Email' },
      { field: 'mobile', header: 'Mobile' },
      { field: 'status', header: 'Status' },
      { field: 'organization', header: 'Organization' }
    ];

    this.users = this.students;
  }

  // [scrollable]="true"
  // scrollHeight="40rem"
}
