# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    working_directory: ~/sunbird-admin-ui
    steps:
      - checkout:
          path: ~/sunbird-admin-ui
      - run:
          name: Install  Node.js v14.20.0 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v14 && nvm use v14 && nvm alias default v14
            node -v
      - run:
          name: Node version
          command: 'node --version'
      - run:
          name: Installing Angular cli
          command: 'npm install -g @angular/cli@14.2.10 --no-progress'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing NPM deps
          command: 'npm install --no-progress'
      - run:
          name: Linting
          command: ng lint

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
