version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-admin-ui
    docker:
      - image: circleci/node:14.0.0
    steps:
      - checkout:
          path: cd sunbird-admin-ui

      - run: npm install
      - run: npm run lint
        #      - run: grunt build-jsdoc

          #
      # - run:
      #     name: running test cases
      #     command: npm run test-player

      - run:
          name: Install NVM
          command: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh|bash'
      
      - run:
          name: linting
          command: npm run lint  
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
