version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/gouravmore/sunbird-admin-ui/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  sunbird-admin-ui:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # ng lint

workflows:
  my-custom-workflow:
    jobs:
      - sunbird-admin-ui